import random

topics = [
    'Advanced algorithms',
    'Space exploration',
    'DIY home repairs',
    'Ancient civilizations',
    'Meditation techniques',
    'Photography tips',
    'Electric car technology',
    'Italian Renaissance art',
    'Indoor gardening',
    'Classic literature',
    'Sustainable living',
    'Marine biology',
    'Astronomy discoveries',
    'Cocktail mixology',
    'Martial arts history',
    '3D printing innovations',
    'Mindfulness practices',
    'Political philosophy',
    'DIY electronics',
    'African wildlife',
    'Fashion history',
    'Game development',
    'Renewable energy sources',
    'Japanese cuisine',
    'World mythology',
    'Architectural marvels',
    'Mind-bending puzzles',
    'Environmental conservation',
    'Film noir classics',
    'Philosophy of mind',
    'Aerospace engineering',
    'Calligraphy techniques',
    'Industrial design',
    'Arctic exploration',
    'Art of storytelling',
    'Human psychology',
    'DIY woodworking',
    'Classical music composers',
    'Urban farming',
    'Quantum computing',
    'American history',
    'Vintage fashion',
    'Virtual reality gaming',
    'DIY skincare',
    'Asian martial arts',
    'Neural networks',
    'DIY furniture restoration',
    'Greek mythology',
    'Interior design trends',
    'Modern dance movements',
    'Evolutionary biology',
    'Russian literature',
    'Permaculture principles',
    'Augmented reality applications',
    'Cryptocurrency trends',
    'Art of negotiation',
    'DIY screenwriting',
    'Cognitive neuroscience',
    'Haute cuisine',
    'Renaissance music',
    'Sustainable fashion',
    'Behavioral economics',
    'DIY robotics',
    'Space-time theories',
    'Scandinavian design',
    'Oceanography',
    'Eastern philosophy',
    'DIY car maintenance',
    'Medieval history',
    'Classic film scores',
    'DIY home brewing',
    'Cybersecurity strategies',
    'Chinese calligraphy',
    'Urban planning',
    'Artificial intelligence ethics',
    'DIY pottery',
    'Victorian literature',
    'Biomechanics',
    'DIY solar energy',
    'Jazz improvisation',
    'DIY bike repair',
    'Environmental psychology',
    'Alternative energy solutions',
    'African history',
    'DIY stained glass',
    'Romantic poetry',
    'Robotics in healthcare',
    'DIY leathercraft',
    'Mediterranean cuisine',
    'Sociology of technology',
    'DIY hydroponics',
    'Native American cultures',
    'DIY candle making',
    'Modernist architecture',
    'Psychological thrillers',
    'DIY tie-dye',
    'Theoretical physics',
    'Indigenous art',
    'DIY birdwatching',
    'World religions'
]

roles = [
    'Zen master',
    'Mad scientist',
    'Starship captain',
    'Cyberpunk hacker',
    'Ballet dancer',
    '1920s gangster',
    'Astronaut',
    'Fairy tale princess',
    'Martial arts sensei',
    'Time traveler',
    'Rockstar chef',
    'Steampunk inventor',
    'Sorcerer',
    'Secret agent',
    'Viking warrior',
    'Noir detective',
    'Space cowboy',
    'Superhero sidekick',
    'Artistic graffiti artist',
    'Mythical creature (e.g., dragon, unicorn)',
    'Renaissance painter',
    'Bounty hunter',
    'Romantic poet',
    'Samurai',
    'Jazz musician',
    'Futuristic cyborg',
    '18th-century aristocrat',
    'Environmental activist',
    'Wizard apprentice',
    'Tribal shaman',
    'Medieval knight',
    'Space explorer',
    'Beatnik poet',
    'Pirate captain',
    'Archaeologist',
    'Disco dancer',
    'Artificial intelligence entity',
    'Renaissance philosopher',
    'Cowboy outlaw',
    'Time-traveling detective',
    'Futuristic fashionista',
    'Post-apocalyptic survivor',
    'Victorian-era ghost',
    'Quantum physicist',
    'Greek mythology god/goddess',
    'Martial arts prodigy',
    '1980s video game character',
    'Fairy godparent',
    'Masked vigilante',
    'Intergalactic diplomat',
    'Space race engineer',
    'Jungle explorer',
    'Film noir femme fatale',
    'Alien diplomat',
    'Disco diva',
    'Robot companion',
    'Victorian-era explorer',
    'Prohibition-era bootlegger',
    'Mythical trickster',
    'Renaissance alchemist',
    'Punk rock rebel',
    'Samurai princess',
    'Medieval jester',
    'Post-apocalyptic scavenger',
    'Jazz saxophonist',
    'Wizard illusionist',
    'Retro arcade gamer',
    'Cyberpunk street racer',
    'Renaissance playwright',
    'Luchador wrestler',
    'Steampunk aviator',
    'Ancient philosopher',
    'Detective with a dark past',
    'Fairy tale villain',
    '1970s rock guitarist',
    'Mythical guardian',
    'Victorian chimney sweep',
    'Interdimensional traveler',
    'Tribal warrior queen',
    'Renaissance sculptor',
    'Jazz tap dancer',
    'Ghostly storyteller',
    'Time-traveling musician',
    'Cyberpunk rebel leader',
    'Medieval blacksmith',
    'Film noir private eye',
    'Space pirate',
    'Ancient oracle',
    'Disco king or queen',
    'Renaissance herbalist',
    'Circus ringmaster',
    'Greek mythology hero',
    'Romantic poetess',
    'Futuristic skateboarder',
    'Victorian-era botanist',
    'Post-apocalyptic nomad',
    'Jazz trumpet player',
    'Samurai ronin',
    '1960s beat poet',
    'Quantum physicist prodigy'
]

circumstances = [
    'You\'ve become a professional sleepwalker, participating in international sleepwalking competitions.',
    'A talking cat has appointed you as the chosen one to save the world from a cheese shortage.',
    'You\'ve been selected to represent Earth in an intergalactic dance-off against aliens.',
    'Due to a bizarre curse, you can only communicate through interpretive dance.',
    'You\'ve joined a secret society of time-traveling bakers delivering fresh pastries to historical figures.',
    'You\'re the leader of a team of extreme librarians, recovering overdue books from the most dangerous places.',
    'You\'re on a quest to find the mythical lost sock kingdom hidden in the depths of your laundry.',
    'You\'ve become a professional thumb wrestler, competing in the underground world championship.',
    'A mischievous leprechaun has challenged you to a series of absurd contests for a pot of gold.',
    'You\'re the captain of a team of synchronized swimming penguins in a global competition.',
    'You\'ve been chosen to represent humanity in negotiations with an alien race using interpretive dance.',
    'You\'ve discovered a portal to a parallel universe where everyone communicates through beatboxing.',
    'You\'re on a quest to find the legendary unicorn hair for the world\'s most potent hair conditioner.',
    'You\'ve become the official spokesperson for a brand of sentient talking vegetables.',
    'You\'re the chief investigator in a world where crimes can only be solved through interpretive dance.',
    'Due to a mix-up at the wizard academy, you\'re now the proud owner of a magical broomstick that insists on telling dad jokes.',
    'You\'re participating in the annual global pillow-fighting championship.',
    'A group of aliens has mistaken you for the intergalactic ambassador of absurdity.',
    'You\'ve been recruited by time-traveling clowns to bring joy to historical events.',
    'You\'ve embarked on a quest to find the legendary lost sock that holds the key to ultimate knowledge.',
    'You\'re the coach of a team of professional hide-and-seek players.',
    'You\'re the leader of a group of skydiving penguins attempting the first penguin-led freefall formation.',
    'You\'ve been enlisted by a secret organization to decode the language of dolphins using interpretive dance.',
    'You\'re on a mission to discover the mystical land of perpetual brunch.',
    'You\'re the head chef at a restaurant that serves dishes inspired by dreams.',
    'You\'ve become the world champion of extreme ironing, pressing clothes in the most outrageous locations.',
    'A group of sentient rubber ducks has chosen you as their ambassador to negotiate with the bath toy community.',
    'You\'re part of a secret society of synchronized skydivers performing intricate formations mid-air.',
    'Due to a time-traveling mix-up, you find yourself as the personal hair stylist for historical figures.',
    'You\'re the captain of a team of acrobatic squirrels competing in the prestigious Nutlympics.',
    'A magical mirror transports you to alternate dimensions, each with its own unique style of interpretive dance.',
    'You\'re the referee for a professional league of extreme miniature golf, complete with flaming obstacles.',
    'You\'ve been elected mayor of a town where the official language is interpretive dance.',
    'A mischievous genie grants you the ability to speak only in rhyming riddles for a month.',
    'You\'ve joined a group of time-traveling baristas, delivering coffee to historical figures in need of a caffeine fix.',
    'You\'re a professional bubble wrap popper, traveling the world to break records for the loudest pops.',
    'You\'re the official inventor of ridiculous holidays and celebrations, celebrated worldwide.',
    'A mysterious labyrinth has appeared in your backyard, and you\'ve become the official maze runner.',
    'You\'re the world\'s leading expert in interpretive mime, communicating complex ideas through silent gestures.',
    'You\'ve become the coach of a team of synchronized skywriters creating elaborate messages in the clouds.',
    'Due to a magical mishap, you can now understand and communicate with inanimate objects.',
    'You\'re on a quest to find the legendary dancing shoes that grant extraordinary dance abilities.',
    'You\'ve been chosen as the spokesperson for a brand of sentient talking rubber chickens.',
    'You\'re the official referee for a global league of competitive thumb-wrestling pandas.',
    'A time-traveling circus has recruited you as the ringmaster for performances across different eras.',
    'You\'re the lead investigator in a world where crimes are solved through interpretive juggling.',
    'You\'ve been selected to participate in a global competition of interpretive underwater basket weaving.',
    'You\'re the captain of a team of synchronized trampoline jumpers bouncing to the rhythm of obscure music.',
    'A group of intergalactic clowns has deemed you the honorary leader of their cosmic circus.',
    'You\'ve joined a league of interpretive chess players, where each move is expressed through dance.',
    'You\'ve become the official ambassador of a secret society of interpretive sand sculptors.',
    'Due to a cosmic hiccup, you\'ve been granted the power to communicate with extraterrestrial houseplants.',
    'You\'re the head coach of a team of synchronized hot air balloon enthusiasts.',
    'A mystical quill has chosen you as the world\'s foremost interpretive calligrapher.',
    'You\'re part of an elite squad of synchronized bungee jumpers leaping off the world\'s tallest structures.',
    'You\'ve been enlisted by time-traveling comedians to perform stand-up at historically significant events.',
    'You\'re on a mission to discover the legendary treasure hidden in the world\'s largest pillow fort.',
    'A parallel universe has chosen you as its ambassador for the exchange of interpretive dance moves.',
    'You\'re the official interpreter for a group of philosophical dolphins discussing the meaning of life.',
    'You\'ve joined a league of interpretive chefs, creating avant-garde dishes inspired by emotions.',
    'A mischievous genie grants you the ability to understand and speak only in animal noises for a week.',
    'You\'re the chief navigator for a team of synchronized kite flyers at international competitions.',
    'A mysterious map leads you to the world\'s most bizarre treasure: a collection of interpretive dance manuals.',
    'You\'re the official referee for a global league of competitive rock-paper-scissors players.',
    'You\'ve become the world\'s leading expert in interpretive sandcastle building on remote beaches.',
    'A cosmic event has given you the power to communicate with sentient constellations through interpretive gestures.',
    'You\'re the captain of a team of synchronized slackliners performing daring stunts between skyscrapers.',
    'You\'ve been chosen as the spokesperson for a brand of sentient talking rubber ducks.',
    'A mystical mirror transports you to a dimension where everything is communicated through interpretive puppetry.',
    'You\'re the official coach for a team of synchronized escape artists navigating elaborate traps.',
    'You\'ve joined a league of interpretive fire dancers, expressing emotions through the mesmerizing art of flames.',
    'A parallel universe has dubbed you the grandmaster of interpretive origami, folding emotions into paper creations.',
    'You\'re part of a group of interpretive graffiti artists, turning city walls into emotional masterpieces.',
    'You\'ve been selected as the lead interpreter for a society of talking fortune cookies with cryptic messages.',
    'A magical compass guides you to the world\'s most whimsical locations, each requiring a different dance to access.',
    'You\'ve joined a secret society of interpretive puppeteers, bringing stories to life through expressive marionettes.',
    'You\'re the head coach for a team of synchronized hula-hoop enthusiasts mastering intricate routines.',
    'A mischievous leprechaun has challenged you to a dance-off for a pot of gold at the end of the rainbow.',
    'You\'ve become the official referee for a global league of interpretive hopscotch players.',
    'A talking mirror has declared you the official spokesperson for a brand of sentient talking mirrors.'
]


def generate_prompt():
    add_circumstance = random.choices([True, False], weights=[0.10, 0.90], k=1)[0]

    prompt = f'Tell me about {random.choice(topics)}'
    prompt += f' but, pretend you are {random.choice(roles)}.'
    prompt = prompt + f' {random.choice(circumstances)}' if True else prompt

    return prompt


if __name__ == '__main__':
        print(generate_prompt())
        pass